nginx1:
  container_name: nginx1
  ports:
    - "83:80"
  volumes:
    - ./nginx1/:/usr/share/nginx/html
  image: nginx
nginx2:
  container_name: nginx2
  ports:
    - "81:80"
  volumes:
    - ./nginx2:/usr/share/nginx/html:ro
  image: nginx

nginx3:
  container_name: nginx3
  ports:
    - "85:80"
  volumes:
    - ./nginx3:/usr/share/nginx/html:ro
  image: nginx

proxy:
  container_name: myproxy
  image: stevecrozz/haproxy-lua
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  ports:
    - 80:80
    - 9000:9000
  links:
    - nginx1
    - nginx2
    - nginx3

